[variables]
NIXPACKS_BUILD_CMD = "cd dog-writer/backend && pip install -r requirements.txt"

[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip']

[phases.install]
cmds = ['cd dog-writer/backend', 'pip install -r requirements.txt']

[start]
cmd = 'cd dog-writer/backend && python -m uvicorn app:app --host 0.0.0.0 --port $PORT' 